volumes:
  pg_data_foodgram:
  static_foodgram:
  media_foodgram:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_foodgram:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static_foodgram:/backend_static
      - media_foodgram:/app/media
  frontend:
    build: ./frontend/
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_foodgram:/frontend_static
  gateway:
    build: ./nginx/
    env_file: .env
    volumes:
      - static_foodgram:/staticfiles/
      - media_foodgram:/staticfiles/media
    ports:
      - "${EXTERNAL_PORT}:80"
